# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYSReachabilityManagerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LYSReachabilityManagerDemo

  target 'LYSReachabilityManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYSReachabilityManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
